# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Количество материала на 1 единицу услуги",
                        max_digits=10,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Service Material",
                "verbose_name_plural": "Service Materials",
                "db_table": "service_materials",
            },
        ),
        migrations.CreateModel(
            name="ICDCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=500)),
                ("name_ru", models.CharField(blank=True, max_length=500)),
                ("parent_code", models.CharField(blank=True, max_length=10)),
                ("level", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ICD Code",
                "verbose_name_plural": "ICD Codes",
                "db_table": "icd_codes",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="icd_codes_code_1be139_idx"),
                    models.Index(fields=["parent_code"], name="icd_codes_parent__e9ec50_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField(help_text="Дата начала действия")),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Дата окончания действия", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Прайс для конкретного филиала (если null - для всей организации)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelists",
                        to="org.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelists",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price List",
                "verbose_name_plural": "Price Lists",
                "db_table": "pricelists",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("service", "Услуга"),
                            ("piece", "Штука"),
                            ("hour", "Час"),
                            ("visit", "Визит"),
                            ("tooth", "Зуб"),
                            ("unit", "Единица"),
                        ],
                        default="service",
                        max_length=20,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, help_text="Базовая цена", max_digits=12),
                ),
                (
                    "price_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Минимальная цена (если диапазон)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "price_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Максимальная цена (если диапазон)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Ставка НДС (%)", max_digits=5
                    ),
                ),
                (
                    "default_duration",
                    models.IntegerField(default=30, help_text="Длительность в минутах"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2196F3", help_text="Цвет в календаре (hex)", max_length=7
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Изображение для онлайн-записи",
                        null=True,
                        upload_to="services/",
                    ),
                ),
                (
                    "is_expensive",
                    models.BooleanField(
                        default=False, help_text="Дорогая услуга (требует одобрения)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_online_booking", models.BooleanField(default=True)),
                ("requires_materials", models.BooleanField(default=False)),
                ("requires_equipment", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Скидка на услугу в этом прайсе (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "pricelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="services.pricelist",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_items",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Item",
                "verbose_name_plural": "Price Items",
                "db_table": "pricelist_items",
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_categories",
                        to="org.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
                "db_table": "service_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="services.servicecategory",
            ),
        ),
    ]
