# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicematerial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_usages",
                to="warehouse.stockitem",
            ),
        ),
        migrations.AddField(
            model_name="servicematerial",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_materials",
                to="services.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="priceitem",
            unique_together={("pricelist", "service")},
        ),
        migrations.AlterUniqueTogether(
            name="servicecategory",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["organization", "code"], name="services_organiz_9eb693_idx"),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["category", "is_active"], name="services_categor_6a9f2f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("organization", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="servicematerial",
            unique_together={("service", "material")},
        ),
    ]
