# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("position", models.CharField(help_text="Должность", max_length=200)),
                (
                    "specialization",
                    models.CharField(blank=True, help_text="Специализация", max_length=200),
                ),
                ("hire_date", models.DateField(help_text="Дата приёма")),
                ("fire_date", models.DateField(blank=True, help_text="Дата увольнения", null=True)),
                ("iin", models.CharField(blank=True, help_text="ИИН", max_length=20)),
                ("passport_series", models.CharField(blank=True, max_length=20)),
                ("passport_number", models.CharField(blank=True, max_length=20)),
                ("passport_issued_by", models.CharField(blank=True, max_length=500)),
                ("passport_issued_date", models.DateField(blank=True, null=True)),
                (
                    "commission_percent",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Процент комиссии", max_digits=5
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Оклад", max_digits=12, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#2196F3", help_text="Цвет в календаре (hex)", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="org.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="org.branch",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_assignments",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Branch Assignment",
                "verbose_name_plural": "Employee Branch Assignments",
                "db_table": "employee_branches",
                "unique_together": {("employee", "branch")},
            },
        ),
        migrations.CreateModel(
            name="EmployeeService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Индивидуальная цена (если отличается от стандартной)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_assignments",
                        to="staff.employee",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Service",
                "verbose_name_plural": "Employee Services",
                "db_table": "employee_services",
                "unique_together": {("employee", "service")},
            },
        ),
    ]
