# Generated by Django 5.0.1 on 2025-11-04 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org", "0001_initial"),
        ("staff", "0002_step1_rename_position"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalarySchemaTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Название шаблона", max_length=200)),
                (
                    "pct_of_own_sales",
                    models.BooleanField(default=False, help_text="Процент от собственных продаж"),
                ),
                (
                    "pct_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Значение процента",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "direction_bonus_enabled",
                    models.BooleanField(default=False, help_text="Бонус за направление"),
                ),
                (
                    "direction_bonus_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент бонуса за направление",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "pct_per_created_visits_enabled",
                    models.BooleanField(default=False, help_text="Процент за созданные визиты"),
                ),
                (
                    "pct_per_visit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент за визит",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fixed_salary_enabled",
                    models.BooleanField(default=False, help_text="Фиксированный оклад"),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Сумма оклада",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="KZT", help_text="Валюта", max_length=3)),
                (
                    "min_rate_enabled",
                    models.BooleanField(default=False, help_text="Минимальная ставка"),
                ),
                (
                    "min_rate_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Минимальная сумма",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "honor_patient_discount_enabled",
                    models.BooleanField(default=False, help_text="Учитывать скидку пациенту"),
                ),
                (
                    "subscription_services_pct_enabled",
                    models.BooleanField(default=False, help_text="Процент от услуг по абонементам"),
                ),
                (
                    "subscription_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Процент от абонементов",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "calc_from_profit_instead_of_revenue",
                    models.BooleanField(
                        default=False, help_text="Расчёт от прибыли вместо выручки"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Salary Schema Template",
                "verbose_name_plural": "Salary Schema Templates",
                "db_table": "salary_schema_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="access_template_id",
            field=models.IntegerField(blank=True, help_text="ID шаблона прав доступа", null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="calendar_color",
            field=models.CharField(
                default="#2196F3", help_text="Цвет в календаре (hex)", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="can_accept_payments",
            field=models.BooleanField(default=False, help_text="Может принимать оплату"),
        ),
        migrations.AddField(
            model_name="employee",
            name="can_be_assistant",
            field=models.BooleanField(default=False, help_text="Может быть ассистентом"),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="description",
            field=models.TextField(blank=True, help_text="Описание"),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(
                choices=[("active", "Активен"), ("fired", "Уволен"), ("on_leave", "В отпуске")],
                default="active",
                help_text="Статус трудоустройства",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="fired_at",
            field=models.DateField(blank=True, help_text="Дата увольнения", null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="hired_at",
            field=models.DateField(blank=True, help_text="Дата приёма", null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="inn",
            field=models.CharField(blank=True, help_text="ИНН", max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_cashier",
            field=models.BooleanField(default=False, help_text="Кассир"),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_chief_accountant",
            field=models.BooleanField(default=False, help_text="Главный бухгалтер"),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_org_head",
            field=models.BooleanField(default=False, help_text="Руководитель организации"),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_user_enabled",
            field=models.BooleanField(default=False, help_text="Разрешить доступ к системе"),
        ),
        migrations.AddField(
            model_name="employee",
            name="limit_goods_sales_today_only",
            field=models.BooleanField(default=False, help_text="Финансы только за текущий день"),
        ),
        migrations.AddField(
            model_name="employee",
            name="markup_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Персональная наценка на услуги (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="min_gap_between_days_hours",
            field=models.IntegerField(
                blank=True, help_text="Минимальный перерыв между днями (часы)", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="min_gap_between_visits_minutes",
            field=models.IntegerField(
                blank=True, help_text="Минимальный перерыв между визитами (минуты)", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="online_slot_step_minutes",
            field=models.IntegerField(
                blank=True, help_text="Индивидуальный шаг онлайн-записи (минуты)", null=True
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="power_of_attorney_date",
            field=models.DateField(blank=True, help_text="Дата доверенности", null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="power_of_attorney_number",
            field=models.CharField(blank=True, help_text="Номер доверенности", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="show_in_schedule",
            field=models.BooleanField(default=True, help_text="Показывать в расписании"),
        ),
        migrations.AddField(
            model_name="employee",
            name="snils",
            field=models.CharField(blank=True, help_text="СНИЛС", max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_employees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Закреплённый склад",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="warehouse.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="warehouse_lock",
            field=models.BooleanField(default=False, help_text="Закрепить за сотрудником склад"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="color",
            field=models.CharField(
                default="#2196F3", help_text="Цвет в календаре (legacy)", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Процент комиссии (legacy)", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="fire_date",
            field=models.DateField(blank=True, help_text="Дата увольнения (legacy)", null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, help_text="Дата приёма (legacy)", null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position_legacy",
            field=models.CharField(
                blank=True, help_text="Должность (legacy field for migration)", max_length=200
            ),
        ),
        migrations.CreateModel(
            name="EmployeeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Название результата", max_length=200)),
                ("comment", models.TextField(blank=True, help_text="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_results",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Result",
                "verbose_name_plural": "Employee Results",
                "db_table": "employee_results",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeSalarySchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("starts_at", models.DateField(help_text="Дата начала действия")),
                (
                    "ends_at",
                    models.DateField(blank=True, help_text="Дата окончания действия", null=True),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Активна")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_salary_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_schemas",
                        to="staff.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Salary Schema",
                "verbose_name_plural": "Employee Salary Schemas",
                "db_table": "employee_salary_schemas",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(help_text="Название задачи", max_length=500)),
                ("description", models.TextField(blank=True, help_text="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В процессе"),
                            ("done", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        help_text="Статус",
                        max_length=20,
                    ),
                ),
                ("deadline_at", models.DateTimeField(help_text="Дедлайн")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="Дата завершения", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        help_text="Исполнитель",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to="staff.employee",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Автор",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_tasks",
                        to="org.organization",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        help_text="Результат",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="staff.employeeresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Task",
                "verbose_name_plural": "Employee Tasks",
                "db_table": "employee_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTaskAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(help_text="Файл", upload_to="task_attachments/%Y/%m/%d/"),
                ),
                ("filename", models.CharField(help_text="Имя файла", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="staff.employeetask",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_task_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Attachment",
                "verbose_name_plural": "Task Attachments",
                "db_table": "employee_task_attachments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeTaskComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.TextField(help_text="Комментарий")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="staff.employeetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Comment",
                "verbose_name_plural": "Task Comments",
                "db_table": "employee_task_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Название должности", max_length=200)),
                ("comment", models.TextField(blank=True, help_text="Комментарий")),
                (
                    "hidden_in_schedule_filter",
                    models.BooleanField(default=False, help_text="Скрыть из фильтра в расписании"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "db_table": "positions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeResultPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.employeeresult"
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.position"
                    ),
                ),
            ],
            options={
                "verbose_name": "Result Position Assignment",
                "verbose_name_plural": "Result Position Assignments",
                "db_table": "employee_result_positions",
            },
        ),
        migrations.AddField(
            model_name="employeeresult",
            name="positions",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_results",
                through="staff.EmployeeResultPosition",
                to="staff.position",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                help_text="Должность",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employees",
                to="staff.position",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "employment_status"], name="employees_organiz_4f239d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "position"], name="employees_organiz_d147c6_idx"
            ),
        ),
        migrations.AddField(
            model_name="salaryschematemplate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_templates",
                to="org.organization",
            ),
        ),
        migrations.AddField(
            model_name="employeesalaryschema",
            name="salary_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_assignments",
                to="staff.salaryschematemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="employeetask",
            index=models.Index(
                fields=["organization", "assignee", "status"], name="employee_ta_organiz_028ba7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetask",
            index=models.Index(
                fields=["organization", "deadline_at"], name="employee_ta_organiz_6f73b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeetask",
            index=models.Index(
                fields=["status", "deadline_at"], name="employee_ta_status_99593e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="employeeresultposition",
            unique_together={("result", "position")},
        ),
    ]
