# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sms_sender",
                    models.CharField(blank=True, help_text="SMS sender name", max_length=50),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="organization/logos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="ClinicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inn", models.CharField(blank=True, max_length=20, verbose_name="ИНН")),
                ("kpp", models.CharField(blank=True, max_length=20, verbose_name="КПП")),
                ("ogrn", models.CharField(blank=True, max_length=20, verbose_name="ОГРН")),
                (
                    "legal_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Юридическое название"
                    ),
                ),
                ("legal_address", models.TextField(blank=True, verbose_name="Юридический адрес")),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                (
                    "support_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email поддержки"),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон поддержки"),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, verbose_name="Номер лицензии"),
                ),
                (
                    "license_issued_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата выдачи лицензии"),
                ),
                (
                    "license_issued_by",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Кем выдана лицензия"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinic_info",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic Info",
                "verbose_name_plural": "Clinic Info",
                "db_table": "clinic_info",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("timezone", models.CharField(default="Asia/Almaty", max_length=50)),
                ("work_hours_from", models.TimeField(default="09:00")),
                ("work_hours_to", models.TimeField(default="20:00")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "branches",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(default="#2196F3", help_text="Hex color code", max_length=7),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "db_table": "rooms",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chair", "Dental Chair"),
                            ("equipment", "Equipment"),
                            ("room", "Room"),
                            ("other", "Other"),
                        ],
                        default="chair",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="org.branch",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="org.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource",
                "verbose_name_plural": "Resources",
                "db_table": "resources",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="org.branch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "db_table": "settings",
                "unique_together": {("organization", "branch", "key")},
            },
        ),
    ]
