# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Appointment Resource",
                "verbose_name_plural": "Appointment Resources",
                "db_table": "appointment_resources",
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ]
                    ),
                ),
                ("time_from", models.TimeField()),
                ("time_to", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
                "db_table": "availabilities",
                "ordering": ["weekday", "time_from"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_datetime", models.DateTimeField(db_index=True)),
                ("end_datetime", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("booked", "Забронировано"),
                            ("confirmed", "Подтверждено"),
                            ("in_progress", "В процессе"),
                            ("done", "Выполнено"),
                            ("no_show", "Не пришёл"),
                            ("canceled", "Отменено"),
                        ],
                        db_index=True,
                        default="booked",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False, help_text="Первичный приём")),
                ("is_urgent", models.BooleanField(default=False, help_text="Срочный")),
                ("note", models.TextField(blank=True, help_text="Примечание к записи")),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="org.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment",
                "verbose_name_plural": "Appointments",
                "db_table": "appointments",
                "ordering": ["start_datetime"],
            },
        ),
    ]
