# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar", "0002_initial"),
        ("org", "0001_initial"),
        ("patients", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="org.room",
            ),
        ),
        migrations.AddField(
            model_name="appointmentresource",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_resources",
                to="calendar.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentresource",
            name="resource",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment_allocations",
                to="org.resource",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="staff.employee",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="availabilities",
                to="org.room",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["branch", "start_datetime"], name="appointment_branch__a023e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["employee", "start_datetime"], name="appointment_employe_8dfda3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "start_datetime"], name="appointment_patient_92fbd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "start_datetime"], name="appointment_status_9da63e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentresource",
            unique_together={("appointment", "resource")},
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("employee", "weekday", "time_from")},
        ),
    ]
