# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0002_initial"),
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="visits.visit",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="billing.invoice",
            ),
        ),
    ]
