# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("org", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(choices=[("M", "Мужской"), ("F", "Женский")], max_length=1),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "iin",
                    models.CharField(blank=True, db_index=True, help_text="ИИН", max_length=20),
                ),
                (
                    "documents",
                    models.JSONField(
                        blank=True, default=dict, help_text="Документы (паспорт и т.д.)"
                    ),
                ),
                (
                    "consents",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Согласия (обработка данных, фото и т.д.)",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Баланс (предоплата/долг)",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Индивидуальная скидка (%)",
                        max_digits=5,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Примечания")),
                ("allergies", models.TextField(blank=True, help_text="Аллергии")),
                ("medical_history", models.TextField(blank=True, help_text="Анамнез")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patients",
                        to="org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "db_table": "patients",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="PatientFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("medical_record", "Medical Record"),
                            ("lab_result", "Lab Result"),
                            ("image", "Image"),
                            ("xray", "X-Ray"),
                            ("consent", "Consent Form"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="patients/%Y/%m/")),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_patient_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient File",
                "verbose_name_plural": "Patient Files",
                "db_table": "patient_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("parent", "Родитель"),
                            ("guardian", "Опекун"),
                            ("spouse", "Супруг(а)"),
                            ("child", "Ребенок"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("documents", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="representatives",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Representative",
                "verbose_name_plural": "Patient Representatives",
                "db_table": "patient_representatives",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["iin"], name="patients_iin_6f34a1_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["organization", "phone"], name="patients_organiz_e51b57_idx"
            ),
        ),
    ]
