# Generated by Django 5.0.1 on 2025-11-04 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        ("services", "0002_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("relation", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_contact_persons",
            },
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("diagnosis", models.TextField()),
                (
                    "is_primary",
                    models.BooleanField(
                        default=True, help_text="Первичный - True, Повторный - False"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.employee",
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.icdcode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_diagnoses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PatientDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("diagnosis", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.employee",
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.icdcode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_diseases",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientDoseLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("study_type", models.CharField(help_text="Вид исследования", max_length=200)),
                (
                    "dose",
                    models.DecimalField(
                        decimal_places=2, help_text="Эффективная доза, мЗв", max_digits=10
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dose_loads",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_dose_loads",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PatientPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "phone_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Мобильный"),
                            ("home", "Домашний"),
                            ("work", "Рабочий"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_phones",
            },
        ),
        migrations.CreateModel(
            name="PatientSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("vk", "VKontakte"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                        ],
                        max_length=50,
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_social_networks",
            },
        ),
    ]
