# Generated by Django 5.0.1 on 2025-11-04 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
        ("services", "0002_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("relation", models.CharField(help_text="Степень родства", max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Contact Person",
                "verbose_name_plural": "Patient Contact Persons",
                "db_table": "patient_contact_persons",
            },
        ),
        migrations.CreateModel(
            name="PatientDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("diagnosis", models.TextField(help_text="Заключительный диагноз")),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "Первичный"), ("2", "Повторный")], default="1", max_length=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_diagnoses",
                        to="staff.employee",
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.icdcode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Diagnosis",
                "verbose_name_plural": "Patient Diagnoses",
                "db_table": "patient_diagnoses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PatientDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(help_text="Дата начала наблюдения")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Дата прекращения наблюдения", null=True
                    ),
                ),
                ("diagnosis", models.TextField(help_text="Диагноз")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="staff.employee",
                    ),
                ),
                (
                    "icd_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.icdcode",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diseases",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Disease",
                "verbose_name_plural": "Patient Diseases",
                "db_table": "patient_diseases",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PatientPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mobile", "Мобильный"),
                            ("home", "Домашний"),
                            ("work", "Рабочий"),
                            ("other", "Другой"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_phones",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Phone",
                "verbose_name_plural": "Patient Phones",
                "db_table": "patient_phones",
            },
        ),
        migrations.CreateModel(
            name="PatientSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("vk", "VKontakte"),
                            ("other", "Другое"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Social Network",
                "verbose_name_plural": "Patient Social Networks",
                "db_table": "patient_social_networks",
            },
        ),
    ]
