# Generated by Django 5.0.1 on 2025-11-04 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendar", "0002_initial"),
        ("org", "0001_initial"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В процессе"),
                            ("completed", "Завершён"),
                            ("canceled", "Отменён"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, help_text="Комментарий врача")),
                (
                    "is_patient_arrived",
                    models.BooleanField(default=False, help_text="Пациент пришёл"),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("diagnosis", models.TextField(blank=True)),
                ("treatment_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit",
                        to="calendar.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit",
                "verbose_name_plural": "Visits",
                "db_table": "visits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitPrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("medication", models.CharField(max_length=500)),
                ("dosage", models.CharField(max_length=200)),
                ("frequency", models.CharField(max_length=200)),
                ("duration_days", models.IntegerField()),
                ("instructions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Prescription",
                "verbose_name_plural": "Visit Prescriptions",
                "db_table": "visit_prescriptions",
            },
        ),
        migrations.CreateModel(
            name="VisitResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("used_time", models.IntegerField(help_text="Usage time in minutes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="org.resource"
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Resource",
                "verbose_name_plural": "Visit Resources",
                "db_table": "visit_resources",
            },
        ),
        migrations.CreateModel(
            name="VisitService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("qty", models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tooth_number",
                    models.CharField(blank=True, help_text="Номер зуба", max_length=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visit_services",
                        to="services.icdcode",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visit_services",
                        to="services.service",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visit Service",
                "verbose_name_plural": "Visit Services",
                "db_table": "visit_services",
            },
        ),
    ]
